#types of arguments or parameters in functions
#position type; keyword type ; default type and variable length arguments
#positin type: it detects according to position
def person(name,age):
    print(name)
    print(age)
person('suresh',28)

output:
/home/ansible-practice/PycharmProjects/test/venv/bin/python /home/ansible-practice/PycharmProjects/test/1.py
suresh
28

Process finished with exit code 0
================================================================================
#keyword type: even it does not has order , i t can detect according to keyword
def person(name,age):
    print(name)
    print(age)
person(age, name)

output:
/home/ansible-practice/PycharmProjects/test/venv/bin/python /home/ansible-practice/PycharmProjects/test/1.py
Traceback (most recent call last):
  File "/home/ansible-practice/PycharmProjects/test/1.py", line 5, in <module>
    person(age, name)
NameError: name 'age' is not defined

Process finished with exit code 1
================================================================


#keyword type: even it does not has order , i t can detect according to keyword
def person(name,age):
    print(name)
    print(age)
person(age = 28 , name='suresh')

output:
/home/ansible-practice/PycharmProjects/test/venv/bin/python /home/ansible-practice/PycharmProjects/test/1.py
suresh
28

Process finished with exit code 0
==================================================================

#default type: if any one of the actual detail is not given , by default it takes what we mentioned in the formal details

def person(name='suresh',age=18):
    print(name)
    print(age)
person('kumar')

output:
/home/ansible-practice/PycharmProjects/test/venv/bin/python /home/ansible-practice/PycharmProjects/test/1.py
kumar
18

Process finished with exit code 0
=================================================================
#varible length : here , if we dont know the length
def sum(a,b):
    c=a+b
    print(c)
sum(2,7)
output:
/home/ansible-practice/PycharmProjects/test/venv/bin/python /home/ansible-practice/PycharmProjects/test/1.py
9

Process finished with exit code 0
=============================================
#varible length : here , if we dont know the length
def sum(a,b):
    c=a+b
    print(c)
sum(2,7,8,17)
output:
/home/ansible-practice/PycharmProjects/test/venv/bin/python /home/ansible-practice/PycharmProjects/test/1.py
Traceback (most recent call last):
  File "/home/ansible-practice/PycharmProjects/test/1.py", line 5, in <module>
    sum(2,7,8,17)
TypeError: sum() takes 2 positional arguments but 4 were given

Process finished with exit code 1
==================================================================
#varible length : here , if we dont know the length
def sum(a,*b):
    print(a)
    print(b)
    c=a
    for i in range(len(b)):
        d = c + b[i]
        c=d
    print(c)
sum(2,7,8,17,66)
output:
/home/ansible-practice/PycharmProjects/test/venv/bin/python /home/ansible-practice/PycharmProjects/test/1.py
2
(7, 8, 17, 66)
100

Process finished with exit code 0
====================================================================
#varible length : here , if we dont know the length
def sum(*b):
    print(b)
    c=0
    for i in range(len(b)):
        d = c + b[i]
        c=d
    print(c)
sum(2,7,8,17,66)
output:
/home/ansible-practice/PycharmProjects/test/venv/bin/python /home/ansible-practice/PycharmProjects/test/1.py
(2, 7, 8, 17, 66)
100

Process finished with exit code 0
==================================================================
a=10
def person(name,*data):
    print(name)
    print(data)

person('suresh',28,'guntur',8790923747)

output:
/home/ansible-practice/PycharmProjects/test/venv/bin/python /home/ansible-practice/PycharmProjects/test/1.py
suresh
(28, 'guntur', 8790923747)

Process finished with exit code 0
================================================
#but we dont the details belong to which one
def person(name,**data):
    print(name)
    print(data)

person('suresh',age=28,proper='guntur',number=8790923747)
output:
/home/ansible-practice/PycharmProjects/test/venv/bin/python /home/ansible-practice/PycharmProjects/test/1.py
suresh
{'age': 28, 'proper': 'guntur', 'number': 8790923747}

Process finished with exit code 0
=========================================================================
#but we dont the details belong to which one
def person(name,**data):
    print(name)
    for i,j in data.items():
        print(i,j)
person('suresh',age=28,proper='guntur',number=8790923747)
output:
/home/ansible-practice/PycharmProjects/test/venv/bin/python /home/ansible-practice/PycharmProjects/test/1.py
suresh
age 28
proper guntur
number 8790923747

Process finished with exit code 0



